# Generated by Django 6.0.6 on 2026-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_alter_matiere_id'),
        ('classes', '0002_alter_classe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, related_name='matieres', to='classes.classe'),
            preserve_default=False,
        ),
    ]
