# Generated by Django 6.0.3 on 2026-08-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_alter_matiere_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='notation',
            field=models.IntegerField(default=20, help_text='La notation maximale pour cette matière', validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
