# Generated by Django 6.0.3 on 2026-08-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classe_enseignant'),
        ('matieres', '0003_matiere_notation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='notation',
        ),
        migrations.AddField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='matieres', to='classes.classe'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1, help_text='Poids de la matière dans le calcul de la moyenne'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='note_sur',
            field=models.PositiveIntegerField(default=20, help_text='Barème de notation de la matière (ex: 5, 10, 20)'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
