# Generated by Django 6.0.3 on 2026-04-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_classe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eleves/')),
                ('statut', models.CharField(choices=[('REGULIER', 'Régulier'), ('IRREGULIER', 'Irrégulier')], max_length=20)),
                ('age', models.IntegerField()),
                ('date_naissance', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
            ],
        ),
    ]
