# Generated by Django 6.0.3 on 2026-04-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='age',
        ),
    ]
