# Generated by Django 6.0.3 on 2026-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='identification_number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
