# Generated by Django 6.0.3 on 2026-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='inscription_date',
            field=models.DateField(),
        ),
    ]
