# Generated by Django 6.0.3 on 2026-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_alter_student_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
