# Generated by Django 6.0.3 on 2026-07-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0005_alter_parent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=110),
        ),
    ]
