# Generated by Django 6.0.6 on 2026-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0006_alter_parent_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='acte_naissance',
            field=models.FileField(blank=True, null=True, upload_to='eleves/actes_naissance/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de l'élève, affichée sur le bulletin (facultative).", null=True, upload_to='eleves/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_identite',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/photos_identite/'),
        ),
    ]
