# Generated by Django 6.0.6 on 2026-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0007_student_acte_naissance_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
    ]
