# Generated by Django 6.0.6 on 2026-08-24, hand-adjusted to backfill
# unique portal_token values for existing Parent rows.

import uuid

from django.db import migrations, models


def backfill_portal_tokens(apps, schema_editor):
    Parent = apps.get_model("eleves", "Parent")
    for parent in Parent.objects.all():
        parent.portal_token = uuid.uuid4()
        parent.save(update_fields=["portal_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0008_student_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_portal_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='parent',
            name='portal_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
