# Generated by Django 6.0.6 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0009_parent_portal_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
