# Generated by Django 6.0.3 on 2026-08-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='enseignant',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
