# Generated by Django 6.0.3 on 2026-08-24 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classe_enseignant'),
        ('eleves', '0009_parent_portal_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('parent_notifie', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='classes.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.student')),
            ],
            options={
                'ordering': ['-date', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='presence_unique_par_jour')],
            },
        ),
    ]
