# Generated by Django 6.0.6 on 2026-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Établissement scolaire', max_length=150)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('nom_directeur', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': "Configuration de l'école",
            },
        ),
    ]
