# Generated by Django 6.0.6 on 2026-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoleconfig',
            name='signature_directeur',
            field=models.ImageField(blank=True, help_text='Signature du directeur, affichée automatiquement sur tous les bulletins.', null=True, upload_to='ecole/signatures/'),
        ),
    ]
