# Generated by Django 6.0.6 on 2026-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ecoleconfig_signature_directeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoleconfig',
            name='annee_scolaire_active',
            field=models.CharField(default='2026-2027', help_text='Année scolaire en cours. Avance automatiquement lors du passage en classe supérieure.', max_length=20),
        ),
    ]
