# Generated by Django 6.0.6 on 2026-08-11 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classe_enseignant'),
        ('eleves', '0006_alter_parent_first_name'),
        ('matieres', '0004_alter_matiere_options_remove_matiere_notation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee_scolaire', models.CharField(default='2026-2027', max_length=20)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('avis_conseil', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='classes.classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'mois', 'annee_scolaire'), name='bulletin_unique_par_mois')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee_scolaire', models.CharField(default='2026-2027', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matieres.matiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.student')),
            ],
            options={
                'ordering': ['matiere__nom'],
                'constraints': [models.UniqueConstraint(fields=('student', 'matiere', 'mois', 'annee_scolaire'), name='note_unique_par_mois')],
            },
        ),
    ]
