# Generated by Django 6.0.6 on 2026-09-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
        ('matieres', '0004_alter_matiere_options_remove_matiere_notation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_parent', models.TextField()),
                ('valeur_proposee', models.DecimalField(blank=True, decimal_places=2, help_text="Valeur corrigée proposée/validée par l'enseignant.", max_digits=5, null=True)),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('transmise', "Transmise à l'enseignant"), ('validee_enseignant', "Validée par l'enseignant"), ('rejetee', "Rejetée par l'enseignant"), ('traitee', 'Traitée')], default='nouvelle', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='bulletins.bulletin')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='matieres.matiere')),
                ('note', models.ForeignKey(blank=True, help_text='Note visée au moment du signalement (si elle existait déjà).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='bulletins.note')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
