# Generated by Django 6.0.6 on 2026-09-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_reclamation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire_cloturee', models.CharField(max_length=20)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('resultats', models.JSONField(default=list, help_text="Liste figée : élève, classe d'origine, moyenne annuelle, décision, classe de destination.")),
                ('realisee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_execution'],
            },
        ),
    ]
