# Generated by Django 6.0.6 on 2026-08-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_classe_enseignant'),
        ('eleves', '0008_student_sexe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('toutes_les_classes', models.BooleanField(default=False)),
                ('nb_destinataires', models.PositiveIntegerField(default=0)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='notifications', to='classes.classe')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Renseigné uniquement pour un envoi ciblé à un seul parent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='eleves.parent')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
